### ISSUE TITLE
Cannot pull Docker image

### ISSUE THREAD

**Issue by Vayel** [departement-loire-atlantique/publik#1]
Hi!

I get this error when I run `docker pull julienbayle/publik` on ArchLinux:

```
Error response from daemon: manifest for julienbayle/publik:latest not found: manifest unknown: manifest unknown
```

Thanks

**Comment by julien-bayle** [comment]
Please use tags as there is one docker image for each module :
https://hub.docker.com/r/julienbayle/publik/tags

For instance :
```docker pull julienbayle/publik:prod-fargo```
